// FIFA World Cup 2026 Annex C assignments, in reverse lexicographic order of the 495 eight-group combinations.
const ASSIGNMENT_ROWS = [
  "EJIFHGLKHGIDJFLKEJIDHGLKEJIDHFLKEGIDJFLKEGJDHFLKEGIDHFLKEGJDHFLIEGJDHFIKHGICJFLKEJICHGLKEJICHFLKEGICJFLKEGJCHFLKEGICHFLK",
  "EGJCHFLIEGJCHFIKHGICJDLKCJIDHFLKCGIDJFLKCGJDHFLKCGIDHFLKCGJDHFLICGJDHFIKEJICHDLKEGICJDLKEGJCHDLKEGICHDLKEGJCHDLIEGJCHDIK",
  "CJEDIFLKCJEDHFLKCEIDHFLKCJEDHFLICJEDHFIKCGEDJFLKCGEDIFLKCGEDJFLICGEDJFIKCGEDHFLKCGJDHFLECGJDHFEKCGEDHFLICGEDHFIKCGJDHFEI",
  "HJBFIGLKEJIBHGLKEJBFIHLKEJBFIGLKEJBFHGLKEGBFIHLKEJBFHGLIEJBFHGIKHJBDIGLKHJBDIFLKIGBDJFLKHGBDJFLKHGBDIFLKHGBDJFLIHGBDJFIK",
  "EJBDIHLKEJBDIGLKEJBDHGLKEGBDIHLKEJBDHGLIEJBDHGIKEJBDIFLKEJBDHFLKEIBDHFLKEJBDHFLIEJBDHFIKEGBDJFLKEGBDIFLKEGBDJFLIEGBDJFIK",
  "EGBDHFLKHGBDJFLEHGBDJFEKEGBDHFLIEGBDHFIKHGBDJFEIHJBCIGLKHJBCIFLKIGBCJFLKHGBCJFLKHGBCIFLKHGBCJFLIHGBCJFIKEJBCIHLKEJBCIGLK",
  "EJBCHGLKEGBCIHLKEJBCHGLIEJBCHGIKEJBCIFLKEJBCHFLKEIBCHFLKEJBCHFLIEJBCHFIKEGBCJFLKEGBCIFLKEGBCJFLIEGBCJFIKEGBCHFLKHGBCJFLE",
  "HGBCJFEKEGBCHFLIEGBCHFIKHGBCJFEIHJBCIDLKIGBCJDLKHGBCJDLKHGBCIDLKHGBCJDLIHGBCJDIKCJBDIFLKCJBDHFLKCIBDHFLKCJBDHFLICJBDHFIK",
  "CGBDJFLKCGBDIFLKCGBDJFLICGBDJFIKCGBDHFLKCGBDHFLJHGBCJFDKCGBDHFLICGBDHFIKHGBCJFDIEJBCIDLKEJBCHDLKEIBCHDLKEJBCHDLIEJBCHDIK",
  "EGBCJDLKEGBCIDLKEGBCJDLIEGBCJDIKEGBCHDLKHGBCJDLEHGBCJDEKEGBCHDLIEGBCHDIKHGBCJDEICJBDEFLKCEBDIFLKCJBDEFLICJBDEFIKCEBDHFLK",
  "CJBDHFLECJBDHFEKCEBDHFLICEBDHFIKCJBDHFEICGBDEFLKCGBDJFLECGBDJFEKCGBDEFLICGBDEFIKCGBDJFEICGBDHFLECGBDHFEKHGBCJFDECGBDHFEI",
  "HJIFAGLKEJIAHGLKEJIFAHLKEJIFAGLKEGJFAHLKEGIFAHLKEGJFAHLIEGJFAHIKHJIDAGLKHJIDAFLKIGJDAFLKHGJDAFLKHGIDAFLKHGJDAFLIHGJDAFIK",
  "EJIDAHLKEJIDAGLKEGJDAHLKEGIDAHLKEGJDAHLIEGJDAHIKEJIDAFLKHJEDAFLKHEIDAFLKHJEDAFLIHJEDAFIKEGJDAFLKEGIDAFLKEGJDAFLIEGJDAFIK",
  "HGEDAFLKHGJDAFLEHGJDAFEKHGEDAFLIHGEDAFIKHGJDAFEIHJICAGLKHJICAFLKIGJCAFLKHGJCAFLKHGICAFLKHGJCAFLIHGJCAFIKEJICAHLKEJICAGLK",
  "EGJCAHLKEGICAHLKEGJCAHLIEGJCAHIKEJICAFLKHJECAFLKHEICAFLKHJECAFLIHJECAFIKEGJCAFLKEGICAFLKEGJCAFLIEGJCAFIKHGECAFLKHGJCAFLE",
  "HGJCAFEKHGECAFLIHGECAFIKHGJCAFEIHJICADLKIGJCADLKHGJCADLKHGICADLKHGJCADLIHGJCADIKCJIDAFLKHJFCADLKHFICADLKHJFCADLIHJFCADIK",
  "CGJDAFLKCGIDAFLKCGJDAFLICGJDAFIKHGFCADLKCGJDAFLHHGJCAFDKHGFCADLIHGFCADIKHGJCAFDIEJICADLKHJECADLKHEICADLKHJECADLIHJECADIK",
  "EGJCADLKEGICADLKEGJCADLIEGJCADIKHGECADLKHGJCADLEHGJCADEKHGECADLIHGECADIKHGJCADEICJEDAFLKCEIDAFLKCJEDAFLICJEDAFIKHEFCADLK",
  "HJFCADLEHJECAFDKHEFCADLIHEFCADIKHJECAFDICGEDAFLKCGJDAFLECGJDAFEKCGEDAFLICGEDAFIKCGJDAFEIHGFCADLEHGECAFDKHGJCAFDEHGECAFDI",
  "HJBAIGLKHJBAIFLKIJBFAGLKHJBFAGLKHGBAIFLKHJBFAGLIHJBFAGIKEJBAIHLKEJBAIGLKEJBAHGLKEGBAIHLKEJBAHGLIEJBAHGIKEJBAIFLKEJBFAHLK",
  "EIBFAHLKEJBFAHLIEJBFAHIKEJBFAGLKEGBAIFLKEJBFAGLIEJBFAGIKEGBFAHLKHJBFAGLEHJBFAGEKEGBFAHLIEGBFAHIKHJBFAGEIIJBDAHLKIJBDAGLK",
  "HJBDAGLKIGBDAHLKHJBDAGLIHJBDAGIKIJBDAFLKHJBDAFLKHIBDAFLKHJBDAFLIHJBDAFIKFJBDAGLKIGBDAFLKFJBDAGLIFJBDAGIKHGBDAFLKHGBDAFLJ",
  "HGBDAFJKHGBDAFLIHGBDAFIKHGBDAFIJEJBAIDLKEJBDAHLKEIBDAHLKEJBDAHLIEJBDAHIKEJBDAGLKEGBAIDLKEJBDAGLIEJBDAGIKEGBDAHLKHJBDAGLE",
  "HJBDAGEKEGBDAHLIEGBDAHIKHJBDAGEIEJBDAFLKEIBDAFLKEJBDAFLIEJBDAFIKHEBDAFLKHJBDAFLEHJBDAFEKHEBDAFLIHEBDAFIKHJBDAFEIEGBDAFLK",
  "EGBDAFLJEGBDAFJKEGBDAFLIEGBDAFIKEGBDAFIJHGBDAFLEHGBDAFEKHGBDAFEJHGBDAFEIIJBCAHLKIJBCAGLKHJBCAGLKIGBCAHLKHJBCAGLIHJBCAGIK",
  "IJBCAFLKHJBCAFLKHIBCAFLKHJBCAFLIHJBCAFIKCJBFAGLKIGBCAFLKCJBFAGLICJBFAGIKHGBCAFLKHGBCAFLJHGBCAFJKHGBCAFLIHGBCAFIKHGBCAFIJ",
  "EJBAICLKEJBCAHLKEIBCAHLKEJBCAHLIEJBCAHIKEJBCAGLKEGBAICLKEJBCAGLIEJBCAGIKEGBCAHLKHJBCAGLEHJBCAGEKEGBCAHLIEGBCAHIKHJBCAGEI",
  "EJBCAFLKEIBCAFLKEJBCAFLIEJBCAFIKHEBCAFLKHJBCAFLEHJBCAFEKHEBCAFLIHEBCAFIKHJBCAFEIEGBCAFLKEGBCAFLJEGBCAFJKEGBCAFLIEGBCAFIK",
  "EGBCAFIJHGBCAFLEHGBCAFEKHGBCAFEJHGBCAFEIIJBCADLKHJBCADLKHIBCADLKHJBCADLIHJBCADIKCJBDAGLKIGBCADLKCJBDAGLICJBDAGIKHGBCADLK",
  "HGBCADLJHGBCADJKHGBCADLIHGBCADIKHGBCADIJCJBDAFLKCIBDAFLKCJBDAFLICJBDAFIKHFBCADLKCJBDAFLHHJBCAFDKHFBCADLIHFBCADIKHJBCAFDI",
  "CGBDAFLKCGBDAFLJCGBDAFJKCGBDAFLICGBDAFIKCGBDAFIJCGBDAFLHHGBCAFDKHGBCAFDJHGBCAFDIEJBCADLKEIBCADLKEJBCADLIEJBCADIKHEBCADLK",
  "HJBCADLEHJBCADEKHEBCADLIHEBCADIKHJBCADEIEGBCADLKEGBCADLJEGBCADJKEGBCADLIEGBCADIKEGBCADIJHGBCADLEHGBCADEKHGBCADEJHGBCADEI",
  "CEBDAFLKCJBDAFLECJBDAFEKCEBDAFLICEBDAFIKCJBDAFEIHFBCADLEHEBCAFDKHJBCAFDEHEBCAFDICGBDAFLECGBDAFEKCGBDAFEJCGBDAFEIHGBCAFDE",
].join("");

const WINNER_GROUP_ORDER = ["A", "B", "D", "E", "G", "I", "K", "L"];
const WINNER_MATCH_BY_GROUP = { A: 79, B: 85, D: 81, E: 74, G: 82, I: 77, K: 87, L: 80 };

function buildCombinationKeys() {
  const groups = "ABCDEFGHIJKL";
  const combinations = [];

  function visit(start, selected) {
    if (selected.length === 8) {
      combinations.push(selected);
      return;
    }
    for (let index = start; index <= groups.length - (8 - selected.length); index += 1) {
      visit(index + 1, selected + groups[index]);
    }
  }

  visit(0, "");
  return combinations.reverse();
}

const COMBINATION_KEYS = buildCombinationKeys();

export function getOfficialThirdPlaceAssignments(qualifiedGroups) {
  const key = [...qualifiedGroups].sort().join("");
  const combinationIndex = COMBINATION_KEYS.indexOf(key);
  if (combinationIndex < 0) return new Map();

  const assignment = ASSIGNMENT_ROWS.slice(combinationIndex * 8, combinationIndex * 8 + 8);
  return new Map(WINNER_GROUP_ORDER.map((winnerGroup, index) => [
    WINNER_MATCH_BY_GROUP[winnerGroup],
    assignment[index]
  ]));
}
